export {GithubApi} from './GitHubApi/GithubApi';
export {GithubGraphQl} from './GithubGraphQl/GithubGraphQl';
export {GithubGraphQl2} from './GithubGraphQl/GithubGraphQl2';
export {GrapghQlPract} from './GithubGraphQl/CorrectWay/GrapghQlPract';
export {GrapghQlGithub} from './SecondDay/GrapghQlGithub';
export {GithuHubPractice} from './SecondDay/GithuHubPractice';
export {ThirdMutation} from './ThirdMutation/ThirdMutation';
export {QueryGithub} from './FourthDay/QueryGithub';
export {MutationGithub} from './FourthDay/MutationGithub';
export {MutationPratcie} from './Fifth/MutationPratcie'